### PR TITLE
Separate MPLAB and Docs folders + Remove unused FreeRTOS files + MPLAB build and upload action

### PR DESCRIPTION
**Pull request by Rockman18**
MPLAB build action only build the project but doesn't upload binary hex files yet. I'm still working on it

### CODE REVIEW

**Comment by virtualabs** [comment]
That's huge ! However, it seems to break the GH pages documentation generation (certainly because the documentation folder has been changed/moved).

**Comment by Rockman18** [comment]
No I don't have moved the "docs" folder... only repack MPLAB files into the "cutcutgo.X" folder. Have a look at my repo, the github-pages are generated correctly. It seems to be a authentication problem with your build-pages action.

`remote: Permission to virtualabs/cutcutgo.git denied to github-actions[bot].
  fatal: unable to access 'https://github.com/virtualabs/cutcutgo.git/': The requested URL returned error: 403
  Error: Action failed with "The process '/usr/bin/git' failed with exit code 128"`

**Comment by virtualabs** [comment]
I'm a total noob with Github action so yes, must be on my side though.

**Comment by Rockman18** [comment]
Wait a little bit before merge. I'm trying an upload of the hex file

**Comment by Rockman18** [comment]
It's operational. I think you can merge.
You will find the binaries directly under the artifacts section, on the "Build firmware binaries" action page. (e.g. : https://github.com/Rockman18/cutcutgo/actions/runs/5445501551)
This action is triggered on push.
It seems that there is a retention duration (90 days max)

Next time I will work on a "Release" action to tag and publish the binaries without limit.

**Pull request merged**
